// core/sdf/include/CAD_0/sdf/mesh_extract.hpp
//
// Mesh extraction from SDF fields.
//
// Two algorithms:
//
// 1. Marching Cubes (Lorensen & Cline 1987) — uniform grid, fast, produces
//    watertight triangulations for closed SDFs. We use the standard 256-entry
//    edge table. Vertex positions are linearly interpolated along edges
//    using the SDF values.
//
// 2. Dual Contouring (Ju et al. 2002) — adaptive, preserves sharp features
//    by placing vertices inside cells at the intersection of the surface
//    and the cell's edge crossing points. NOT IMPLEMENTED in Phase B.5
//    (deferred — see ADR-0015 for rationale).
//
// The Marching Cubes implementation here:
//   * Evaluates the SDF on a regular grid inside `body.bounds()` + padding
//   * Resolves each cube's 8 corner signs via the 256-entry edge table
//   * Linearly interpolates vertex positions along edges
//   * Optionally computes per-vertex normals from the SDF gradient
//
// Phase B.5 enhancements:
//   * Vertex welding via spatial hash — eliminates duplicate vertices
//     generated by neighbouring cells sharing the same edge crossing.
//     Reduces vertex count by ~90% (285k → ~30k for res=64).
//   * Narrow-band culling — skip cells whose 8 corners all have the same
//     sign (no surface crossing). Avoids ~75% of empty cube evaluations
//     for compact SDFs.
//
// Output is a triangle mesh stored as interleaved vertex positions and
// optional vertex normals. The mesh is watertight for closed SDFs.
//
#pragma once

#include "CAD_0/sdf/field.hpp"
#include "CAD_0/math/vec.hpp"
#include "CAD_0/math/bbox.hpp"

#include <cstdint>
#include <optional>
#include <vector>

namespace CAD_0::sdf {

// Triangle mesh — positions + optional normals + indices.
//
// Layout: positions[i] = Vec3f at vertex i; indices[3*t], indices[3*t+1],
// indices[3*t+2] form triangle t. If normals is non-empty, normals[i] is
// the per-vertex normal at vertex i.
struct TriangleMesh {
    std::vector<math::Vec3f> positions;
    std::vector<math::Vec3f> normals;
    std::vector<std::uint32_t> indices;  // triplets forming triangles

    std::size_t vertex_count() const noexcept { return positions.size(); }
    std::size_t triangle_count() const noexcept { return indices.size() / 3; }

    bool is_watertight_candidate() const noexcept {
        // A watertight mesh has every edge shared by exactly 2 triangles.
        // This is a cheap sanity check; full watertightness validation is
        // the responsibility of core/brep/validate.hpp (Phase D).
        return indices.size() % 3 == 0 && !positions.empty();
    }
};

// Options for marching cubes extraction.
struct MarchingCubesOptions {
    std::uint32_t resolution = 64;        // voxels per axis
    bool compute_normals = true;          // compute per-vertex normals from SDF gradient
    bool weld_vertices = true;           // deduplicate vertices via spatial hash

    // Weld tolerance: two vertices within this distance (in grid units)
    // are merged. Set to 0 to disable welding (Phase B behavior).
    // Default: 1e-5 * cell_size — small enough to avoid false merges.
    float weld_tolerance_scale = 1e-5f;
};

// Marching cubes extraction (legacy signature, defaults to Phase B.5 options).
TriangleMesh marching_cubes(const SDFBody& body,
                            std::uint32_t resolution = 64,
                            bool compute_normals = true);

// Same as above but takes an explicit bounds override. Useful for
// infinite SDFs (PlaneSDF) where body.bounds() returns universe.
TriangleMesh marching_cubes(const SDFBody& body,
                            const math::Bboxf& bounds,
                            std::uint32_t resolution = 64,
                            bool compute_normals = true);

// Phase B.5: full-control extraction with options.
TriangleMesh marching_cubes(const SDFBody& body,
                            const math::Bboxf& bounds,
                            const MarchingCubesOptions& opts);

// Phase B.5: weld vertices of an existing mesh in-place.
// Two vertices within `tolerance` (in mesh units) are merged into one.
// Indices are remapped. Normals are averaged if present.
//
// Returns the number of vertices after welding.
std::size_t weld_vertices(TriangleMesh& mesh, float tolerance);

} // namespace CAD_0::sdf

