// core/geometry/include/cadforge/geometry/shape_id.hpp
//
// Persistent shape identification — genealogy-based naming.
// See ADR-0005 — "Persistent naming by genealogy + subshape tracing".
//
// CRITICAL CORRECTION vs. original proposal:
//   Original idea  : "firma geometrica + genealogia"
//   Problem        : "firma geometrica" does not survive fillet/chamfer,
//                    parameter changes, or boolean operations.
//   Corrected     : Genealogy only. Subshape identification is done
//                    by tracing the operation that created a subshape,
//                    not by matching its geometric signature.
//
// The ShapeId is composed of:
//   1. FeatureId    — stable, generated by the feature that owns this shape
//   2. SubshapeRef  — reference to a sub-region identified by tracing
//                     the operation that created it (op-history)
//   3. Generation   — rebuild counter, used to invalidate stale references
//
// References: Andrade 1998 (cell-tuple), Chen & Luo 2010 (subshape history).
//
#pragma once

#include <cadforge/config.h>

#include <cstdint>
#include <functional>
#include <string>

namespace cadforge::geometry {

// Stable identifier of a feature in the feature tree.
// Survives across rebuilds — only invalidates if the user deletes the
// feature explicitly.
struct FeatureId {
    std::uint64_t value{0};

    constexpr FeatureId() = default;
    explicit constexpr FeatureId(std::uint64_t v) noexcept : value(v) {}

    constexpr bool operator==(const FeatureId&) const noexcept = default;
    constexpr bool operator!=(const FeatureId&) const noexcept = default;
    constexpr bool operator<(const FeatureId& o) const noexcept { return value < o.value; }
};

// Reference to a subshape within a feature's output.
// Encodes the path from the feature's root output down to a specific
// subshape (vertex/edge/face of a B-Rep, leaf node of an SDF tree).
//
// Path components are 32-bit indices into the operation's output map
// at each level. Path length is unbounded but in practice < 4.
struct SubshapeRef {
    static constexpr std::uint8_t kMaxDepth = 8;

    std::uint32_t path[kMaxDepth]{};
    std::uint8_t  depth{0};

    constexpr SubshapeRef() = default;

    SubshapeRef push(std::uint32_t idx) const noexcept {
        SubshapeRef r = *this;
        if (r.depth < kMaxDepth) {
            r.path[r.depth] = idx;
            ++r.depth;
        }
        return r;
    }

    constexpr bool operator==(const SubshapeRef&) const noexcept = default;
};

// Generation counter — incremented on every rebuild of the feature tree.
// A reference is stale if its generation < current feature-tree generation.
struct Generation {
    std::uint32_t value{0};
    constexpr Generation() = default;
    explicit constexpr Generation(std::uint32_t v) noexcept : value(v) {}
    constexpr bool operator==(const Generation&) const noexcept = default;
};

// A persistent, stable identifier for any subshape in the model.
struct ShapeId {
    FeatureId    feature;
    SubshapeRef  subshape;
    Generation   generation;

    constexpr bool operator==(const ShapeId&) const noexcept = default;

    std::string to_string() const;
    bool is_stale_relative_to(Generation current) const noexcept {
        return generation.value < current.value;
    }
};

// Hashing for use in std::unordered_map
struct ShapeIdHash {
    std::size_t operator()(const ShapeId& id) const noexcept {
        const auto h1 = std::hash<std::uint64_t>{}(id.feature.value);
        const auto h2 = std::hash<std::uint32_t>{}(id.subshape.path[0]);
        return h1 ^ (h2 + 0x9e3779b9 + (h1 << 6) + (h1 >> 2));
    }
};

} // namespace cadforge::geometry
