// CAD_0/config.h.in — generated by CMake at configure time
#pragma once

#define CAD_0_VERSION_MAJOR 0
#define CAD_0_VERSION_MINOR 1
#define CAD_0_VERSION_PATCH 0
#define CAD_0_VERSION_STRING "0.1.0"

/* #undef CAD_0_BUILD_PYTHON */
#define CAD_0_BUILD_TESTING  1
#define CAD_0_USE_TBB        1
/* #undef CAD_0_SANITIZE */
